# Generated by Django 3.0.3 on 2020-02-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('column', models.CharField(max_length=30, verbose_name='专栏')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('uploader', models.CharField(default='admin', max_length=20, verbose_name='发布者')),
            ],
        ),
    ]
